# Generated by Django 3.2.4 on 2021-06-16 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('cod_carro', models.IntegerField(primary_key=True, serialize=False, verbose_name='Codigo de Carro')),
                ('fecha_creacion', models.DateField(verbose_name='Fecha de Creacion')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('run', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Rut Cliente')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre Cliente')),
                ('apellido', models.CharField(max_length=20, verbose_name='Apellido Cliente')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('contraseña', models.CharField(max_length=50, verbose_name='Contraseña')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('cod_producto', models.IntegerField(primary_key=True, serialize=False, verbose_name='Codigo de Producto')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre de Producto')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('stock', models.IntegerField(verbose_name='Stock')),
                ('descripcion', models.CharField(max_length=1000, verbose_name='Descripcion')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Foto Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Producto_Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_venta', models.IntegerField(verbose_name='Precio de Venta')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('cod_carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.carro')),
                ('cod_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
            ],
        ),
        migrations.AddField(
            model_name='carro',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente'),
        ),
    ]
