# Generated by Django 3.2.9 on 2021-11-24 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('run', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Rut Cliente')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('contraseña', models.CharField(max_length=50, verbose_name='Contraseña')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipousuario')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('idpago', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id pago')),
                ('comprobante', models.CharField(max_length=50, verbose_name='Comprobante')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Informes',
            fields=[
                ('idinforme', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id informe')),
                ('tipoinforme', models.CharField(max_length=50, verbose_name='tipo informe')),
                ('idpago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pago')),
            ],
        ),
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('idcita', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Cita')),
                ('hora', models.CharField(max_length=50, verbose_name='Hora')),
                ('estado', models.CharField(max_length=50, verbose_name='Estado')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('idagenda', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Agenda')),
                ('hora', models.CharField(max_length=50, verbose_name='Hora')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
        ),
    ]
