# Generated by Django 3.2.9 on 2021-11-24 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_agenda_citas_informes_pago_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='medicoespecialidad',
            field=models.CharField(max_length=50, null=True, verbose_name='Medico y especialidad'),
        ),
    ]
