# Generated by Django 3.2.9 on 2021-11-25 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_agenda_medicoespecialidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='citas',
            name='idagenda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.agenda'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='citas',
            name='run',
            field=models.CharField(max_length=10, verbose_name='Rut Cliente'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='run',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Rut'),
        ),
    ]
