# Generated by Django 3.2.9 on 2021-11-25 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20211125_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citas',
            name='idagenda',
        ),
    ]
