# Generated by Django 3.2.9 on 2021-11-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_citas_idagenda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citas',
            name='idcita',
        ),
        migrations.AddField(
            model_name='citas',
            name='idagenda',
            field=models.IntegerField(default=1, primary_key=True, serialize=False, verbose_name='Id Agenda'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agenda',
            name='run',
            field=models.CharField(max_length=10, verbose_name='Rut'),
        ),
        migrations.AlterField(
            model_name='citas',
            name='estado',
            field=models.CharField(max_length=50, verbose_name='NOTAS'),
        ),
        migrations.AlterField(
            model_name='citas',
            name='run',
            field=models.CharField(max_length=10, verbose_name='Rut Medico'),
        ),
    ]
